site_name: "Your Cyber Notes"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - assets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - attr_list


nav:
  - Home: index.md
  - Red Team:
      - Overview: red-team/index.md
      - Rooms: red-team/rooms/
      - Cheatsheet: red-team/cheatsheet.md
      - Tools:
          - Nmap: tools/nmap.md
  - Blue Team:
      - Overview: blue-team/index.md
      - Detection Playbooks: blue-team/detection-playbooks.md

