site_name: "Your Cyber Notes"
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
  palette:
    primary: indigo
    accent: indigo

nav:
  - Home: index.md
  - Red Team:
      - Overview: red-team/index.md
      - Rooms: red-team/rooms/
      - Cheatsheet: red-team/cheatsheet.md
      - Tools:
          - Nmap: tools/nmap.md
          # add more red-team tools here later
  - Blue Team:
      - Overview: blue-team/index.md
      - Detection Playbooks: blue-team/detection-playbooks.md
      # add more blue-team pages here later

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
