site_name: "Your Cyber Notes"
site_description: "Red/Blue notes, tools, playbooks and TryHackMe/HTB writeups"
site_author: "Your Name"
repo_url: "https://github.com/yourusername/mkdocs-starter"
theme:
  name: 'material'
  language: 'en'
nav:
  - Home: index.md
  - Red Team:
    - Overview: red-team/readme.md
    - Example Room: red-team/rooms/thm-room-example.md
    - Cheatsheet: red-team/cheatsheet.md
  - Blue Team:
    - Overview: blue-team/readme.md
    - Detection Playbooks: blue-team/detection-playbooks.md
  - Tools:
    - nmap: tools/nmap.md
  - Writeups:
    - Example: writeups/htb-writeup-example.md
plugins:
  - search
markdown_extensions:
  - admonition
  - codehilite
