site_name: "BLUEs Blue Team Field Manual"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - assets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - attr_list


nav:
  - Home: index.md
  - Red Team:
      - Overview: red-team/index.md
      - Reconnaissance: red-team/reconnaissance/index.md
      - Weaponization: red-team/weaponization/index.md
      - Delivery: red-team/delivery/index.md
      - Exploitation: red-team/exploitation/index.md
      - Installation: red-team/installation/index.md
      - Command & Control: red-team/c2/index.md
      - Persistence: red-team/persistence/index.md
      - Privilege Escalation: red-team/priv-esc/index.md
      - Lateral Movement: red-team/lateral-movement/index.md
      - Exfiltration: red-team/exfiltration/index.md
      - Actions on Objectives: red-team/actions/index.md
      - Cheatsheet: red-team/cheatsheet.md
      
  - Blue Team:
      - Overview: blue-team/index.md
      - Detection Playbooks: blue-team/detection-playbooks.md

